server:
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  service:
    general:
      type: LoadBalancer
  persistence:
    storageClass: credify-managed-disks
  serviceAccount:
    name: credifyai-vault
    automountServiceAccountToken: true
  config: |
    disable_mlock = true
    ui = true
    listener "tcp" {
      tls_disable = 1
      address = "[::]:{{ .Values.server.containerPorts.http }}"
      cluster_address = "[::]:{{ .Values.server.containerPorts.internal }}"
      {{- if .Values.server.metrics.enabled }}
      # Enable unauthenticated metrics access (necessary for Prometheus Operator)
      telemetry {
        unauthenticated_metrics_access = "true"
      }
      {{- end }}
    }
    storage "raft" {
      path = "{{ .Values.server.persistence.mountPath }}"
    }
    log_level = "debug"
    service_registration "kubernetes" {}